# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MTKit' do
  # Pods for MTKit
  pod 'YYCache', '~> 1.0.4'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SVProgressHUD', '~> 2.2.5'
  
end
