# Uncomment the next line to define a global platform for your project

   platform :ios, '9.0'

target 'MTKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MTKit
#    pod 'YYCache', '~> 1.0.4'
#    pod 'AFNetworking', '~> 3.1.0'
#    pod 'SVProgressHUD', '~> 2.1.2'
end
